<a href="https://colab.research.google.com/github/alirkorkmaz/Numpy-Tutorial/blob/main/Numpy_%C3%87al%C4%B1%C5%9Fma_Dosyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Çalışma Defteri


In [ ]:
import numpy as np  #numpy kütüphanesinin import edilmesi

In [ ]:
print(np.__version__)   # kütüphanenin  versiyon kontrolü

1.21.6


In [ ]:
arr = np.array([1,2,3,4,5])    # numpy ile oluşturulan array veri tipi
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
sayilar = (1,2,3,4,5)       # tuple veri türünün array veri türüne dönüşmesi
array = np.array(sayilar)
print(array)
print(type(array))
print(type(sayilar))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'tuple'>


In [ ]:
a = np.array(52)    # her bir arrayın eksen sayısı gösterimi
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
'''arr1 = np.array([1,2,3,4,5], ndim = 5)
print(arr1)
print(" ",arr1.ndim)'''

'arr1 = np.array([1,2,3,4,5], ndim = 5)\nprint(arr1)\nprint(" ",arr1.ndim)'

In [ ]:
arr2 = np.array([1,2,3,4,5])   # bir arrayda elemanlara ulaşma 
print(arr2[0])

1


In [ ]:
arr3 = np.array([1,2,3,4])   # arrayda iki elemanın toplamı 
print(arr[2] + arr[3])

7


In [ ]:
arr = np. array([[1,2,3,4,5],[1,2,3,4,5]])  # iki eksenli bir arrayda belirlenen elemana gitme 
print(arr[0,1])

2


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  # üç eksenli bir arrayda belirlenen elemana gitme
print(arr[1,1,2])

12


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])    # arrayda negatif indeksleme ile elemana gitme 
print(arr[1,-2])

9


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])   # bir arrayda iki indeks değeri arasındaki elemanları çağırma
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1,2,3,45,6,6])   # bir arrayda iki indeks değeri arasındaki elemanları çağırma
print(arr[4:])

[6 6]


In [ ]:
arr = np.array([1,2,3,4,5,6]) # bir arrayda iki indeks değeri arasındaki elemanları çağırma
print(arr[:4])

[1 2 3 4]


In [ ]:
arr = np.array([12,3,4,434,5,4])  # bir arrayda iki indeks değeri arasındaki elemanları çağırma
print(arr[-3:-1])

[434   5]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])  # bir arrayda iki indeks değeri arasındaki elemanları çağırma
print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])   # bir arrayda iki indeks değeri arasındaki elemanları çağırma
print(arr[::2])

[1 3 5 7]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  # bir arrayda iki indeks değeri arasındaki elemanları çağırma
print(arr[1, 1:4])

[7 8 9]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])   # bir arrayda iki indeks değeri arasındaki elemanları çağırma
print(arr[0:2, 2]) 

[3 8]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])     # bir arrayda iki indeks değeri arasındaki elemanları çağırma

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Pythonda Veri Türleri

* string:"ABCD"
* integer: -1, -2, 3
* float: 1.2, 42.42
* boolen:True, False
* complex:1.0 + 2.0j, 1.5 + 2.5j

## Numpy Veri Türleri

* i- tam sayı
* b- boole
* u- İşaretsiz tam sayı
* f- float
* c- complex float
* m- timedelta
* M- datetime
* O- obje
* S- string
* U- tek kodlu string
* V- diğer tür için sabit bellek yığını ( void )

In [ ]:
arr = np.array([12,2,3,4])   # arrayın veri tipini bulma 
print(arr.dtype)

int64


In [ ]:
arr = np.array([1,2,3,4,5], dtype = "S")   # arrayın veri tipini değiştirme(bazı değerler arasında gerçeleşir)
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


## Mevcut Dizilerde Veri Türünü Dönüştürme

* Mevcut bir dizinin veri tipini değiştirmenin en iyi yolu, astype() metotu ile dizinin bir kopysını oluşturmaktır.
* İşlev astype(), dizinin bir kopyasını oluşturur ve veri türünü parametre olarak belirtmenize olanak tanır.

In [ ]:
arr = np.array([1.1, 2.1, 3.1]) # float değerlerin int32 değere dönüşümü

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
arr = np.array([1.1, 2.1, 3.1])    # float değerlerin int64 değere dönüşümü

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
import numpy as np
arr = np.array([1, 0, 3, 4, -1])    # int değerin bool değere dönüşümü, 
                                #  sıfır dışındaki tüm değerler True olarak alınıyor
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True  True  True]
bool


## NumPy Array Copy ve View 

#### Kopyalama ve Görünüm Arasındaki Fark


* Bir kopya ile bir dizin arasındaki görünüm farkı, kopyanın yeni bir dizin olması ve görünümün yalnızca orjinal bir dizinin görünümü olmasıdır.
* Kopya verilerin sahibidir ve kopyada yapılan bir değişiklik orjinal diziyi etkilemez. Orjinal veride yapılan değişiklik kopyayı etkilemez.
* View, verilere sahip değildir ve viewde yapılan değişik orjinal diziyi etkiler ve orjinal dizide yapıla herhangi bir değişiklik görünümü etkiler.
* Kopyalar verilere sahiptir, viewler verilere sahip değildir.
* Her numpy dizisi, verilerin sahibiyse base, dönen özniteliğe None sahiptir.
* Aksi takdirde, base  öznitelik orijinal nesneye başvurur.





In [ ]:
arr = np.array([1,2,3,4,5])  # bir arrayın kopyalanması, .copy() fonksiyonu ile kopyada değişiklikler oldu
x = arr.copy()               # orjinal veride bir değişiklik olmadı 
arr[0] = 10

print(arr)
print(x)

[10  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5])    # view() fonkisyonu kullanarak kopyalama, 
x = arr.view()                 # gerçek veride yapılan deişiklik viewi etkiler
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])  # viewde  yapılan deişiklik gerçek veriyi etkiler
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
arr = np.array([1,2,3,4,5])

x = arr.copy()  #base kullanımını araştır
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## NumPy Dizi Şekli


* Bir dizinin şekli, her boyuttaki eleman sayısıdır.



In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8]])  # bir arrayın kaç boyutlu olduğunu öğreniriz
print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1,2,3,4,5], ndmin = 5)  # bir arrayda boyut sayısı arttırma 
print(arr.shape)

(1, 1, 1, 1, 5)


## Dizileri Yeniden Şekillendirme

* Dizi eleman sayısı değiştirilen değer ile örtüşmelidir. Aksi halde valueError yanıtını alır.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])  # 4 satır 3 sütunluk bir array oluşturuldu
newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])  # eksen sayısı eklenerek 3 satır 2 sütunluk array oluşturuldu 

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2,2,2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Diziyi Yineleme

* Yineleme, öğelerden tek tek geçmek anlamına gelir.
* Çok boyutlu dizilerle uğraştığımız için for döngüsü ile yineleme işlemi yapabiliriz.

In [ ]:
arr = np.array([1,2,3]) # for ile arraylari açma
for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])  # for ile arraylari açma
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]]) # for ile arraylari açma, iki eksenli olduğu için for içinde for kullanıldı
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1,2,3], [1,2,3]],[[1,2,3,],[1,2,3]]])  
for x in arr:
  print(x)

[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]


In [ ]:
arr = np.array([[[1,2,3], [1,2,3]],[[1,2,3,],[1,2,3]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
1
2
3
1
2
3
1
2
3


### nditer() Kullanarak Dizileri Yineleme


* Birden fazla for döngüsü kullanmadan nditer() fonksiyonu ile aynı sonuca ulaşabiliriz.

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # iç içe for döngüleri kullanmak yerine tek fonksiyonda arrayları açma 

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


## Farklı Veri Türleriyle Diziyi Yineleme

In [ ]:
arr = np.array([1,2,3])
for x in np.nditer(arr, flags=["buffered"], op_dtypes=["S"]):
  print(x)

b'1'
b'2'
b'3'


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


ndenumerate() kullanarak numaralandırılmış yineleme yapabiliriz

In [ ]:
arr = np.array([1, 2, 3])  # array indekslerini numaralandırma 

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # array indekslerini numaralandırma
 
for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## NumPy Birleştirme Dizisi


* NumPy'de dizileri eksenlere göre birleştiririz.


In [ ]:
arr1 = np.array([1, 2, 3])   # dizinleri eksenlere göre birleştiririz, default olarak soldan sağa birleştirildi

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


* Eksen farkının görülebileceği iki farklı kod.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])  # axis değeri 1 girilerek soldan sağa birleştirildi

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])  # axis değeri 0 girilerek yukardan aşağı birleştirildi

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1 = np.array([1,2,3])   # stack() fonksiyonu ile birleştirilme sağlandı
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1,2,3])   # stack() fonksiyonu ile birleştirilme sağlandı
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


* Satır boyunca istifleme

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


* Sütun boyunca istifleme

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


* Yükseklik boyunca istifleme

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## NumPy Ayırma Dizisi


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])  # array_split ile 3 arraya ayırma 

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])  # array_split ile eşit olmayan ayırma 

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])   # array_split ile array elemanlarına ulaşma 
 
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])  

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)  # array_split ile axis 1 düzeyinde ayırma,
                                         # bölünme gerçekleşmeden önceki her dizinin ilk elemanı ile oluşturuldu 
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)   # bölünme gerçekleşmeden önceki her dizinin ilk elemanı ile oluşturuldu, hsplit kullanıldı

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Dizi Arama


Arnan karakterin liste içinde hangi indekslerde olduğunu yazdırır.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])  # where ile array içindeki elemanı arama 

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])   # where ile array içinde işlem gerçekleştirme 

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


* Karakteri soldan aramaya başlar ve istenen karakterin nereye ekleneceğini gösterir

In [ ]:
import numpy as np 
arr = np.array([6, 7, 8, 9])    # array içindeki karakteri soldan arama yapar

x = np.searchsorted(arr, 7)

print(x)
print(arr)

1
[6 7 8 9]


* Karakteri sağdan aramaya başlar ve istenen karakterin nereye ekleneceğini gösterir

In [ ]:
arr = np.array([6, 7, 8, 9])  # array içindeki karakteri sağdan arama yapar

x = np.searchsorted(arr, 7, side='right')

print(x)
print(arr)

2
[6 7 8 9]


* Birden fazla karakterin eklenmesi için farklı dizinleri verir.

In [ ]:
arr = np.array([1, 3, 5, 7])   # soldan olacak şekilde birden fazla arama yapar 

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## Dizileri Sıralama

In [ ]:
arr = np.array([3, 2, 0, 1])   # arrayları küçükten büyüğe sıralar

print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])  # arrayları alfabeye göre sırlar 

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
arr = np.array([True, False, True])   # bool değere göre sırala, False değeri ilk gelir

print(np.sort(arr))

[False  True  True]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])  # array içindeki dizinleri küçükten büyüğe sıralar 

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Dizileri Filtreleme


* Mevcut bir diziden bazı elemanları alıp onlardan yeni bir dizi oluşturmaya filtreleme denir .
* NumPy'de, bir boolean index list kullanarak bir diziyi filtrelersiniz .



In [ ]:
arr = np.array([41, 42, 43, 44])  # True değerlere denk gelen elemanları farklı bir değişkene atanması 
                                  # ana değişkende eleman sayısında eksilme olmadı 
x = [True, False, True, False]

newarr = arr[x]

print(newarr)
print(arr)

[41 43]
[41 42 43 44]


In [ ]:
arr = np.array([41, 42, 43, 44])  # True değerlerinin alındığı farklı bir gösterim 


filter_arr = []


for element in arr:
  
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])  # True değerlerinin alındığı farklı bir gösterim 


filter_arr = []


for element in arr:
  
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
arr = np.array([41, 42, 43, 44])    # True değerlerinin alındığı farklı bir gösterim 

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])    # True değerlerinin alındığı farklı bir gösterim 

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## Rastgele Sayı Oluştur


In [ ]:
import random


In [ ]:
x = random.randint(100)

print(x)

18


In [ ]:
x = random.rand()

print(x)

0.31221252311038794


In [ ]:
x=random.randint(100, size=(5))

print(x)

[84 41 14 99 96]


In [ ]:
x = random.randint(100, size=(3, 5))

print(x)

[[20 65 50 89 23]
 [45 58 70 72 44]
 [42 89 29 54 85]]


In [ ]:
x = random.rand(5)

print(x)

[0.19211244 0.80120335 0.85015831 0.07730002 0.48432723]


In [ ]:
x = random.rand(3, 5)

print(x)

[[0.69843902 0.74188691 0.67653059 0.07782988 0.70159173]
 [0.83378546 0.67785929 0.00890359 0.34991755 0.54169169]
 [0.83271292 0.87354534 0.10591516 0.30656556 0.78631415]]


In [ ]:
x = random.choice([3, 5, 7, 9])

print(x)

3


In [ ]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 9 7 3 3]
 [9 7 3 9 5]
 [7 9 5 7 5]]


In [ ]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)
# p olasılıkları ile 100 adet seçili sayılardan random değer oluşturma

[5 3 7 7 7 5 5 7 7 7 5 5 7 5 5 7 7 7 7 5 5 7 5 7 7 7 5 7 7 7 5 5 7 7 3 7 5
 7 5 7 5 7 7 5 7 7 7 7 5 7 5 7 7 7 5 7 5 5 7 7 5 5 7 7 5 5 7 7 5 5 5 5 5 5
 5 7 7 7 7 7 7 7 7 7 7 5 7 3 5 7 5 7 7 7 7 5 3 7 7 7]


In [ ]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 3 5 7]
 [7 3 7 5 7]
 [7 5 5 5 7]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)
# dizinin öğelerini rastgele karıştırır. shuffle fonkisyonu gerçekleştirir

[4 5 1 3 2]


In [ ]:
x = random.normal(size=(2, 3))

print(x)

#2x3 rastgele sayı üretir

[[-0.29955149 -2.03656271 -0.74099636]
 [ 0.16210275 -0.01231922  1.91136267]]


In [ ]:
x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)
# ortalamsı 1, standart sapmsaı 2 olan 2x3 sayı üretir

[[-1.9791572  -0.86303527 -1.71228316]
 [ 0.67430238  0.50467672  2.52721121]]


In [ ]:
x = random.poisson(lam=2, size=10)

print(x)

[6 2 4 4 3 1 3 2 0 1]


## NumPy ufuncs


* NumPy'de vektörleştirmeyi uygulamak için kullanılır .
* Vektörleşme Nedir?
* Yinelemeli ifadeleri vektör tabanlı bir işleme dönüştürmeye vektörleştirme denir.
* 2 listeyi toplamak 


In [ ]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [ ]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]
